import json
import pandas as pd
from pathlib import Path

# Load existing JSON
with open('inventory_data.json', 'r') as f:
    data = json.load(f)

# Hardcoded Spanish translations for all items to generate the Spanish Master
es_translations = {
    # bev_alc
    "Stella Artois 6pk": "Stella Artois 6pk",
    "Yuengling Flight 6pk": "Yuengling Flight 6pk",
    "Bud Light 6pk": "Bud Light 6pk",
    "Modelo Negra 6pk": "Modelo Negra 6pk",
    "F5 IPA 6pk": "F5 IPA 6pk",
    "Corona 6pk": "Corona 6pk",
    "Modelo 6pk.": "Modelo 6pk.",

    # bev_bib
    "BIB Coca-Cola": "Caja de Jarabe Coca-Cola",
    "BIB Coke Zero": "Caja de Jarabe Coke Zero",
    "BIB Diet Coke": "Caja de Jarabe Diet Coke",
    "BIB Diet Dr. Pepper": "Caja de Jarabe Diet Dr. Pepper",
    "BIB Dr.Pepper": "Caja de Jarabe Dr. Pepper",
    "BIB Lemonade": "Caja de Jarabe Limonada",
    "BIB Root Beer": "Caja de Jarabe Cerveza de Raíz",
    "BIB Sprite": "Caja de Jarabe Sprite",

    # bev_rtd
    "Tea automatic brew 32/3.5oz.": "Té preparado automático 32/3.5oz.",
    "Jarritos Asst Flavors cs.": "Jarritos Sabores Surtidos caja",
    "Mexican Coca-Cola cs": "Coca-Cola Mexicana caja",
    "Mexican Sprite cs": "Sprite Mexicano caja",

    # cleaning
    "Bleach": "Cloro",
    "Dish Detergent (dawn) ": "Detergente para Platos (Dawn)",
    "Floor cleaner (fabuloso purple)": "Limpiador de Pisos (Fabuloso morado)",
    "Scrubber Stainless Steel 12/1 ct.": "Esponjas de Acero Inoxidable 12/1 ct.",
    "Dining Room Sanitizer": "Desinfectante para Comedor",

    # dairy
    "Butter European 36/1lb.": "Mantequilla Europea 36/1lb.",
    "Butter Unsalted 36/1lb.": "Mantequilla sin Sal 36/1lb.",
    "Buttermilk 1cs.": "Suero de Mantequilla 1 caja",
    "Cream Cheese 10/3lb.": "Queso Crema 10/3lb.",
    "Eggs 15 doz.": "Huevos 15 docenas",
    "Heavy Cream cs.": "Crema Espesa caja",
    "Mozzarella BelGioioso Fresh 2/1lb.": "Mozzarella Fresca BelGioioso 2/1lb.",
    "Mozzarella Loaf 8/6lb.": "Barra de Mozzarella 8/6lb.",
    "Mozzarella Shredded 5lb.": "Mozzarella Rallada 5lb.",
    "Parmesan Grated 5lb.": "Parmesano Rallado 5lb.",
    "Parmesan Shredded 5lb.": "Parmesano en Hebras 5lb.",
    "Ricotta Cheese 6/3lb.": "Queso Ricotta 6/3lb.",
    "Sour Cream 4/5lb.": "Crema Agria 4/5lb.",
    "Sour Cream packets": "Paquetes de Crema Agria",
    "Provolone sliced pkg.": "Provolone en Rebanadas paq.",
    "American Cheese Sliced Yellow pkg.": "Queso Americano Amarillo Rebanado paq.",
    "American Cheese Sliced White pkg.": "Queso Americano Blanco Rebanado paq.",

    # disposables
    "08\" Ultra Lunch Paper Plate": "Plato de Papel Ultra 08\"",
    "10\" Ultra Lunch Paper Plate": "Plato de Papel Ultra 10\"",
    "16 oz. Foam Cup": "Vaso de Espuma 16 oz.",
    "16 oz. Foam Lid": "Tapa para Vaso de Espuma 16 oz.",
    "2 oz. Clear portion cup": "Vasito Transparente para Porción 2 oz.",
    "2 oz. Clear Portion Lid": "Tapa Transparente para Porción 2 oz.",
    "4 oz. Foam Portion Cup": "Vasito de Espuma para Porción 4 oz.",
    "4 oz. Foam Portion Lid": "Tapa de Espuma para Porción 4 oz.",
    "6x6 Clear Plastic togo": "Envase de Plástico Transparente para Llevar 6x6",
    "8x8 Clear togo boxes cs": "Cajas Transparentes para Llevar 8x8 caja",
    "6x6 White Foam togo": "Envase de Espuma Blanca para Llevar 6x6",
    "8x8 White Foam togo": "Envase de Espuma Blanca para Llevar 8x8",
    "9x9 White Foam togo": "Envase de Espuma Blanca para Llevar 9x9",
    "Aluminum Foil Roll": "Rollo de Papel Aluminio",
    "Aluminum Foil Sheets 10.75\" 1/200ct.": "Hojas de Papel Aluminio 10.75\" 1/200 ct.",
    "Aluminum Lid (full Pan)": "Tapa de Aluminio (Bandeja Completa)",
    "Aluminum Lid (half pan)": "Tapa de Aluminio (Media Bandeja)",
    "Aluminum Pan (full pan)": "Bandeja de Aluminio (Completa)",
    "Aluminum Pan (half pan)": "Bandeja de Aluminio (Media)",
    "Cutlery Meal Kit": "Kit de Cubiertos para Comida",
    "Deli container togo 16oz.": "Envase Deli para Llevar 16 oz.",
    "Deli container togo 8oz.": "Envase Deli para Llevar 8 oz.",
    "Deli container togo lids": "Tapas para Envases Deli para Llevar",
    "Film Poly 12\" Wrap": "Envoltura de Película Plástica 12\"",
    "Film Poly 18\" Wrap": "Envoltura de Película Plástica 18\"",
    "Film Poly 24\" Wrap": "Envoltura de Película Plástica 24\"",
    "Fork White Heavy Duty box": "Tenedor Blanco de Alta Resistencia caja",
    "Gloves Lg": "Guantes G",
    "Gloves Med": "Guantes M",
    "Gloves Sm": "Guantes P",
    "Knife White Heavy Duty box": "Cuchillo Blanco de Alta Resistencia caja",
    "Menu Tissue (sgl)": "Papel Seda para Menú (sgl)",
    "Paper Towel (brown roll)": "Toalla de Papel (Rollo Marrón)",
    "Paper Towels (dispenser)": "Toallas de Papel (Dispensador)",
    "Paper Towels (kitchen)": "Toallas de Papel (Cocina)",
    "Pizza Boxes 10\"": "Cajas de Pizza 10\"",
    "Pizza Boxes 14\"": "Cajas de Pizza 14\"",
    "Pizza Boxes 18\"": "Cajas de Pizza 18\"",
    "Portion Control Bag (sandwich size)": "Bolsa de Control de Porción (Tamaño Sándwich)",
    "Register 3 1/8\" Thermal Roll": "Rollo Térmico para Registradora 3 1/8\"",
    "Register paper 3 1/8\" Thermal": "Papel Térmico para Registradora 3 1/8\"",
    "Toilet Tissue": "Papel Higiénico",
    "Trash Bags (kitchen size)": "Bolsas de Basura (Tamaño Cocina)",
    "Trash Bags (Lg 55-65 gal)": "Bolsas de Basura (Grandes 55-65 gal)",
    "Trash Bags (Small)": "Bolsas de Basura (Pequeñas)",
    "Togo T-Shirt Bag Lg.": "Bolsa tipo Camiseta para Llevar G",
    "Togo T-Shirt Bag Med": "Bolsa tipo Camiseta para Llevar M",
    "Togo T-Shirt Bag Sm": "Bolsa tipo Camiseta para Llevar P",

    # frozen.ref
    "Cake Bundt": "Pastel Bundt",
    "Cake Chocolate": "Pastel de Chocolate",
    "Cake Italian Lemon": "Pastel de Limón Italiano",
    "Cake Strawberry": "Pastel de Fresa",
    "Cannoli Cream w/choc": "Crema de Cannoli con Chocolate",
    "Cannoli Shell Lg": "Concha de Cannoli Grande",
    "Cannoli Shell Lg (choc)": "Concha de Cannoli Grande (Choc)",
    "Cannoli Shell Sm": "Concha de Cannoli Pequeña",
    "Cannoli Shell Sm (choc)": "Concha de Cannoli Pequeña (Choc)",
    "Cheesecake NY": "Pastel de Queso estilo NY",
    "Cheesecake Oreo": "Pastel de Queso Oreo",
    "Cheesecake Turtle": "Pastel de Queso Tortuga",
    "French Fries Crinkle Cut": "Papas Fritas Onduladas",
    "French Fries Homestyle": "Papas Fritas Estilo Casero",
    "French Fries Shoestring": "Papas Fritas Finas",
    "Hashbrown 2/10lb.": "Papas Ralladas (Hashbrown) 2/10lb.",
    "Pasta Tortellini": "Pasta Tortellini",
    "Pizza Crust Cauliflower": "Masa de Pizza de Coliflor",
    "Tater Tots": "Croquetas de Papa (Tater Tots)",
    "Tiramisu (ea.)": "Tiramisú (c/u)",
    "French Fries 3/8th\" Straight": "Papas Fritas Rectas 3/8\"",
    "Biscuits 1/24 cs.": "Panecillos 1/24 caja",
    " ": " ",

    # grocery_dry
    "Baguettes": "Baguettes",
    "Basalmic Glaze": "Glaseado Balsámico",
    "Bread Crumbs Panko 25lb.": "Pan Rallado Panko 25lb.",
    "Bread Sliced Sandwich": "Pan de Molde en Rebanadas",
    "Buns Hamburger": "Pan para Hamburguesas",
    "Buns Hot Dog": "Pan para Hot Dogs",
    "Croutons 4/2.5lbs.": "Crutones 4/2.5lbs.",
    "Dressing Caesar 1 gal": "Aderezo César 1 galón",
    "Dressing Italian 1 gal.": "Aderezo Italiano 1 galón",
    "Dressing Mix Italian packet": "Mezcla de Aderezo Italiano en paquete",
    "Dressing Mix Ranch packet": "Mezcla de Aderezo Ranchero en paquete",
    "Dressing Vinagrette 1 gal.": "Vinagreta 1 galón",
    "Flour High Gluten All Trump 25lb.": "Harina de Alto Gluten All Trump 25lb.",
    "Flour High Gluten All Trump 50lb.": "Harina de Alto Gluten All Trump 50lb.",
    "Tortillas Flour 10\"": "Tortillas de Harina 10\"",
    "Fry Oil": "Aceite para Freír",
    "Garlic Minced in water": "Ajo Picado en agua",
    "Garlic Powder 5lb.": "Ajo en Polvo 5lb.",
    "Hot Sauce Red Hot 1 gal.": "Salsa Picante Red Hot 1 galón",
    "Jalapeno Sliced #10": "Jalapeño en Rodajas lata #10",
    "Mayonnaise 4/1 gal.": "Mayonesa 4/1 galón",
    "Olive Ripe Sliced #10 ": "Aceitunas Maduras en Rodajas lata #10 ",
    "Onion minced dried": "Cebolla Picada Seca",
    "Onion Powder": "Cebolla en Polvo",
    "Pan Spray cs": "Aerosol para Sartén caja",
    "Parmesan Packets": "Paquetes de Queso Parmesano",
    "Parsley minced dried": "Perejil Picado Seco",
    "Pasta Fettucine 10\"": "Pasta Fettuccine 10\"",
    "Pasta Lasagna 10\"": "Pasta Lasaña 10\"",
    "Pasta Penne Rigate": "Pasta Penne Rigate",
    "Pasta Rotini Tri Color": "Pasta Rotini Tricolor",
    "Pasta Spaghetti 10\"": "Pasta Espagueti 10\"",
    "Pepperoncini Whole 1 gal.": "Pepperoncini Entero 1 galón",
    "Pineapple tidbits #10": "Trozos de Piña lata #10",
    "Ranch Dressing mix cs.": "Mezcla para Aderezo Ranchero caja",
    "Red Pepper Packets": "Paquetes de Chile Rojo",
    "Salsa Fire Roasted #10": "Salsa Asada al Fuego lata #10",
    "Salt 50lb.": "Sal 50lb.",
    "Sugar 50lb.": "Azúcar 50lb.",
    "Tomato Paste cs.": "Pasta de Tomate caja",
    "Tomato Sauce cs.": "Salsa de Tomate caja",
    "Vinegar Red 1 gal": "Vinagre Tinto 1 galón",
    "Vinegar White 1 gal": "Vinagre Blanco 1 galón",
    "Yeast ": "Levadura",
    "Chocolate for Cannoli #10 can": "Chocolate para Cannoli lata #10",
    "Texas Toast": "Tostada Texana",
    "Everything Bagel": "Bagel Todo (Everything)",
    "Plain Bagel": "Bagel Sencillo",

    # meats
    "Bacon Sliced 1cs": "Tocino en Rebanadas 1 caja",
    "Canadian Bacon": "Tocino Canadiense",
    "Ground Beef 73/27 lbs": "Carne Molida 73/27 lbs",
    "Ground Beef 80/20 lbs": "Carne Molida 80/20 lbs",
    "Ground Beef 90/10 lbs": "Carne Molida 90/10 lbs",
    "Italian Sausage Rope": "Salchicha Italiana en Cuerda",
    "Pepperoni": "Pepperoni",
    "Philly Meat": "Carne para Philly",
    "Chicken Breast": "Pechuga de Pollo",
    "Chicken Wings": "Alitas de Pollo",
    "Bacon Bits ": "Trozos de Tocino ",
    "Shrimp 21-25 raw peeled 5/2lb.": "Camarones 21-25 crudos y pelados 5/2lb.",
    "Brisket": "Pecho de Res (Brisket)",
    "Pork Butt": "Paleta de Cerdo",
    "Polish Sausage": "Salchicha Polaca",
    "Hot Links": "Salchichas Picantes",
    "Hot Dogs": "Hot Dogs",
    "Catfish/Swai cs.": "Bagre/Swai caja",

    # produce
    "Basil Fresh": "Albahaca Fresca",
    "Bell Peppers (Yellow, Red,Orange) 6 pk": "Pimientos (Amarillo, Rojo, Naranja) 6 paq.",
    "Bell Peppers Choppers": "Pimientos para Picar",
    "Broccoli Florets (fresh)": "Flores de Brócoli (frescas)",
    "Broccoli Florets (frozen)": "Flores de Brócoli (congeladas)",
    "Celery 1cs": "Apio 1 caja",
    "Constellation Cherry Tomatoes": "Tomates Cherry Constellation",
    "Cucumber English 2 pk": "Pepino Inglés 2 paq.",
    "Lettuce Romaine": "Lechuga Romana",
    "Mushroom Medium": "Champiñones Medianos",
    "Onion Red": "Cebolla Roja",
    "Onion Yellow": "Cebolla Amarilla",
    "Potato Idaho 70 ct./50 lb.": "Papas Idaho 70 ct./50 lb.",
    "Spinach Fresh": "Espinaca Fresca",
    "Tomato Cherry": "Tomates Cherry",
    "Tomato Roma": "Tomates Roma",

    # prepared
    "Chicken Breast Cooked (4 oz.)": "Pechuga de Pollo Cocida (4 oz.)",
    "Boneless Bites (prepared 8 ea.)": "Trozos sin Hueso (preparados 8 c/u)",
    "Chicken Tenders (prepared 3 ea.)": "Tiras de Pollo (preparadas 3 c/u)",
    "Dough Par Bake 18\"": "Masa Pre-cocida 18\"",
    "Marinara (gal.)": "Salsa Marinara (gal.)",
    "Pizza Sauce (gal.)": "Salsa de Pizza (gal.)",
    "Italian Sausage Cooked (lb.)": "Salchicha Italiana Cocida (lb.)",
    "Onion Diced (qt.)": "Cebolla Cortada en Cubitos (cto.)",
    "Onion Sliced (qt.)": "Cebolla en Rodajas (cto.)",
    "Bell Pepper Chopped (qt.)": "Pimiento Picado (cto.)",
    "Mushroom Sliced (qt)": "Champiñones en Rodajas (cto.)",
    "Tomatos Sliced (qt.)": "Tomates en Rodajas (cto.)",
    "Tomatos Diced (qt.)": "Tomates Cortados en Cubitos (cto.)",
    "Bacon Bits (qt)": "Trozos de Tocino (cto.)",
    "Stromboli (prepared) ea.": "Stromboli (preparado) c/u",
    "Meatballs (ea)": "Albóndigas (c/u)",
    "Fettucine Alfredo (prepared) ea.": "Fettuccine Alfredo (preparado) c/u",
    "Spaghetti w/meatballs (prepared) ea.": "Espaguetis con Albóndigas (preparado) c/u",
    "Chicken Parmesan (prepared) ea.": "Pollo a la Parmesana (preparado) c/u",

    # smallwares
    "Cheese shakers": "Queseros"
}

english_writer = pd.ExcelWriter('item master/English Master.xlsx', engine='openpyxl')
spanish_writer = pd.ExcelWriter('item master/Spanish Master.xlsx', engine='openpyxl')

for cat_id, cat_data in data.items():
    label = cat_data['label']
    items = [item['name'] for item in cat_data['items']]
    spanish_items = [es_translations.get(item, item) for item in items]

    df_en = pd.DataFrame(items)
    df_es = pd.DataFrame(spanish_items)

    df_en.to_excel(english_writer, sheet_name=label, index=False, header=False)
    df_es.to_excel(spanish_writer, sheet_name=label, index=False, header=False)

english_writer.close()
spanish_writer.close()
